// Bakes every human mesh in the catalog (node, two worker threads), caches per-spec results and writes
// src/generated/humans.bin.js: a manifest plus one deflated, base64 blob the game decodes at load.
//   node tools/bake-humans.mjs            (incremental, cached in .cache/humans)
//   node tools/bake-humans.mjs --force    (rebuild everything)
import { Worker, isMainThread, parentPort } from 'worker_threads';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import zlib from 'zlib';
import os from 'os';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

if (!isMainThread) {
  const { buildHumanGeometry } = await import(path.join(ROOT, 'src/entities/humanMesh.js'));
  const { encodeGeometry } = await import(path.join(ROOT, 'src/entities/humanCodec.js'));
  const { decimateHuman } = await import(path.join(ROOT, 'tools/humanDecimate.mjs'));
  parentPort.on('message', ({ id, spec }) => {
    const t0 = Date.now();
    const g = buildHumanGeometry(spec);
    const d = decimateHuman(g, spec);
    const bytes = encodeGeometry(d);
    parentPort.postMessage({ id, bytes, tris: d.tris, verts: d.verts, full: g.userData.tris, ms: Date.now() - t0 }, [bytes.buffer]);
  });
} else {
  const force = process.argv.includes('--force');
  const { bakeList } = await import(path.join(ROOT, 'src/entities/humanCatalog.js'));
  const srcHash = crypto.createHash('sha1');
  for (const f of ['src/entities/humanMesh.js', 'src/entities/humanCodec.js', 'tools/humanDecimate.mjs']) srcHash.update(fs.readFileSync(path.join(ROOT, f)));
  // the rig only matters through its bind pose, so hash that instead of all of character.js
  const { bindPose } = await import(path.join(ROOT, 'src/entities/character.js'));
  for (const [k, w, f] of [[1, 1, false], [0.94, 0.95, true], [1.05, 1.1, false]]) srcHash.update(JSON.stringify(bindPose(k, w, f).map(m => m.elements.map(v => +v.toFixed(6)))));
  const base = srcHash.digest('hex');
  const cacheDir = path.join(ROOT, '.cache/humans');
  fs.mkdirSync(cacheDir, { recursive: true });
  const jobs = bakeList().map(j => ({ ...j, hash: crypto.createHash('sha1').update(base + JSON.stringify(j.spec)).digest('hex').slice(0, 20) }));
  const todo = jobs.filter(j => force || !fs.existsSync(path.join(cacheDir, j.hash + '.bin')));
  console.log(`bake: ${jobs.length} meshes, ${todo.length} to build`);
  const t0 = Date.now();
  if (todo.length) {
    const cores = typeof os.availableParallelism === 'function' ? os.availableParallelism() : os.cpus().length;
    const nw = Math.max(1, Math.min(cores, 6, todo.length));
    // biggest first keeps both workers busy
    todo.sort((a, b) => (a.lod - b.lod) || (a.kind === 'lod' ? -1 : 1));
    let next = 0, done = 0;
    await new Promise((resolve, reject) => {
      for (let w = 0; w < nw; w++) {
        const worker = new Worker(fileURLToPath(import.meta.url));
        const feed = () => { if (next < todo.length) { const j = todo[next++]; worker.postMessage({ id: j.id, spec: j.spec }); } else worker.terminate(); };
        worker.on('message', (m) => {
          const j = jobs.find(x => x.id === m.id);
          fs.writeFileSync(path.join(cacheDir, j.hash + '.bin'), Buffer.from(m.bytes));
          fs.writeFileSync(path.join(cacheDir, j.hash + '.json'), JSON.stringify({ tris: m.tris, verts: m.verts }));
          done++;
          console.log(`  ${String(done).padStart(3)}/${todo.length} ${m.id.padEnd(22)} ${String(m.full).padStart(7)} -> ${String(m.tris).padStart(6)} tris ${String(m.ms).padStart(6)} ms`);
          if (done === todo.length) { worker.terminate(); resolve(); } else feed(); // the last worker must exit too, or node never quits
        });
        worker.on('error', reject);
        feed();
      }
    });
  }
  // assemble
  const parts = [], manifest = [];
  let off = 0, tris = 0;
  for (const j of jobs) {
    const b = fs.readFileSync(path.join(cacheDir, j.hash + '.bin'));
    const meta = JSON.parse(fs.readFileSync(path.join(cacheDir, j.hash + '.json'), 'utf8'));
    manifest.push({ id: j.id, model: j.model, kind: j.kind, name: j.name, lod: j.lod, offset: off, length: b.length, tris: meta.tris });
    parts.push(b); off += b.length; tris += meta.tris;
  }
  const raw = Buffer.concat(parts);
  const packed = zlib.deflateRawSync(raw, { level: 9, memLevel: 9 });
  const b64 = packed.toString('base64');
  fs.mkdirSync(path.join(ROOT, 'src/generated'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'src/generated/humans.bin.js'),
    `// generated by tools/bake-humans.mjs — do not edit\nexport const HUMANS_MANIFEST = ${JSON.stringify(manifest)};\nexport const HUMANS_RAW_BYTES = ${raw.length};\nexport const HUMANS_DATA = "${b64}";\n`);
  const mb = (n) => (n / 1048576).toFixed(2) + ' MB';
  console.log(`bake: raw ${mb(raw.length)}, deflated ${mb(packed.length)}, base64 ${mb(b64.length)}, ${tris} tris total, ${((Date.now() - t0) / 1000).toFixed(1)} s`);
}
